spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
  jpa:
    open-in-view: false
  config:
    import:
    - "optional:classpath:jwt.yaml"
    - "optional:classpath:storage.yaml"
  mvc:
    problemdetails:
      enabled: true